/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './admin.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './admin.component';
import * as i4 from '../services/order.service';
const styles_AdminComponent:any[] = [i0.styles];
export const RenderType_AdminComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AdminComponent,data:{}});
function View_AdminComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(1,(null as any),['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_AdminComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['Admin'])),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(4,0,(null as any),
      (null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['Orders'])),
      (_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(7,0,(null as any),
          (null as any),4,'ul',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),
      (_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_AdminComponent_1)),
      i1.ɵdid(10,802816,(null as any),0,i2.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,
          i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted(-1,
          (null as any),['\n']))],(_ck,_v) => {
    var _co:i3.AdminComponent = _v.component;
    const currVal_0:any = _co.orders;
    _ck(_v,10,0,currVal_0);
  },(null as any));
}
export function View_AdminComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-admin',
      ([] as any[]),(null as any),(null as any),(null as any),View_AdminComponent_0,
      RenderType_AdminComponent)),i1.ɵdid(1,114688,(null as any),0,i3.AdminComponent,
      [i4.OrderService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AdminComponentNgFactory:i1.ComponentFactory<i3.AdminComponent> = i1.ɵccf('app-admin',
    i3.AdminComponent,View_AdminComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9hZG1pbi9hZG1pbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9hZG1pbi9hZG1pbi5jb21wb25lbnQudHMiLCJuZzovLy9GOi9CZWxhamFyQW5ndWxhci9JbnN0YWxsQW5ndWxhci9QZW1yb2dyYW1hbi1XZWItTGFuanV0L1ByYWt0aWt1bTEyL2F1dGgtZGVtby9zcmMvYXBwL2FkbWluL2FkbWluLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9hZG1pbi9hZG1pbi5jb21wb25lbnQudHMuQWRtaW5Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbjxoMT5BZG1pbjwvaDE+XG48aDI+T3JkZXJzPC9oMj5cbjx1bD5cbiAgPGxpICpuZ0Zvcj1cImxldCBvcmRlciBvZiBvcmRlcnNcIj57eyBvcmRlciB9fTwvbGk+XG48L3VsPiIsIjxhcHAtYWRtaW4+PC9hcHAtYWRtaW4+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDSUU7TUFBQSx3RUFBaUM7YUFBQTtJQUFBO0lBQUE7Ozs7b0JBSm5DLDBDQUNBO01BQUE7TUFBQSw0Q0FBSTtNQUFBLFlBQVUsMENBQ2Q7TUFBQTtNQUFBLDhCQUFJO01BQVcsMENBQ2Y7VUFBQTtVQUFBLDhCQUFJO01BQ0Y7YUFBQTs0QkFBQSx5Q0FBaUQ7VUFBQTs7SUFBN0M7SUFBSixZQUFJLFNBQUo7Ozs7b0JDSkY7TUFBQTsrQkFBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
