/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './no-access.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './no-access.component';
const styles_NoAccessComponent:any[] = [i0.styles];
export const RenderType_NoAccessComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NoAccessComponent,data:{}});
export function View_NoAccessComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['Access Denied']))],(null as any),(null as any));
}
export function View_NoAccessComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-no-access',
      ([] as any[]),(null as any),(null as any),(null as any),View_NoAccessComponent_0,
      RenderType_NoAccessComponent)),i1.ɵdid(1,114688,(null as any),0,i2.NoAccessComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NoAccessComponentNgFactory:i1.ComponentFactory<i2.NoAccessComponent> = i1.ɵccf('app-no-access',
    i2.NoAccessComponent,View_NoAccessComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9uby1hY2Nlc3Mvbm8tYWNjZXNzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9CZWxhamFyQW5ndWxhci9JbnN0YWxsQW5ndWxhci9QZW1yb2dyYW1hbi1XZWItTGFuanV0L1ByYWt0aWt1bTEyL2F1dGgtZGVtby9zcmMvYXBwL25vLWFjY2Vzcy9uby1hY2Nlc3MuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9uby1hY2Nlc3Mvbm8tYWNjZXNzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9uby1hY2Nlc3Mvbm8tYWNjZXNzLmNvbXBvbmVudC50cy5Ob0FjY2Vzc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGgxPkFjY2VzcyBEZW5pZWQ8L2gxPiIsIjxhcHAtbm8tYWNjZXNzPjwvYXBwLW5vLWFjY2Vzcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMENBQ0E7TUFBQTtNQUFBLDRDQUFJO01BQUE7OztvQkNESjtNQUFBO2tDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
