/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './not-found.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './not-found.component';
const styles_NotFoundComponent:any[] = [i0.styles];
export const RenderType_NotFoundComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NotFoundComponent,data:{}});
export function View_NotFoundComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  not-found works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_NotFoundComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-not-found',
      ([] as any[]),(null as any),(null as any),(null as any),View_NotFoundComponent_0,
      RenderType_NotFoundComponent)),i1.ɵdid(1,114688,(null as any),0,i2.NotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NotFoundComponentNgFactory:i1.ComponentFactory<i2.NotFoundComponent> = i1.ɵccf('app-not-found',
    i2.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9CZWxhamFyQW5ndWxhci9JbnN0YWxsQW5ndWxhci9QZW1yb2dyYW1hbi1XZWItTGFuanV0L1ByYWt0aWt1bTEyL2F1dGgtZGVtby9zcmMvYXBwL25vdC1mb3VuZC9ub3QtZm91bmQuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC50cy5Ob3RGb3VuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBub3QtZm91bmQgd29ya3MhXG48L3A+XG4iLCI8YXBwLW5vdC1mb3VuZD48L2FwcC1ub3QtZm91bmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSwrQ0FFQztNQUFBOzs7b0JDRko7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
