/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9CZWxhamFyQW5ndWxhci9JbnN0YWxsQW5ndWxhci9QZW1yb2dyYW1hbi1XZWItTGFuanV0L1ByYWt0aWt1bTEyL2F1dGgtZGVtby9zcmMvYXBwL2FwcC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
