/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovQmVsYWphckFuZ3VsYXIvSW5zdGFsbEFuZ3VsYXIvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC9QcmFrdGlrdW0xMi9hdXRoLWRlbW8vc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
